name: 🐛 Bug Report
description: Report a bug encountered while using Magnum Cluster API driver
body:
  - type: textarea
    id: problem
    attributes:
      label: What steps did you take and what happened?
      description: |
        Please provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner.
      placeholder: "A clear and concise description on how to REPRODUCE the bug."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: osVersion
    attributes:
      label: Openstack version
      placeholder: "The version of the Openstack."
    validations:
      required: true

  - type: textarea
    id: capiVersion
    attributes:
      label: Magnum Cluster API driver version
      placeholder: "The version of the Magnum Cluster API driver used in the environment."
    validations:
      required: true

  - type: textarea
    id: coeClusterTemplate
    attributes:
      label: COE Cluster Template
      placeholder: "The COE Cluster Template used. `openstack coe cluster template show --format json CLUSTER_TEMPLATE_NAME`"

  - type: textarea
    id: coeCluster
    attributes:
      label: COE Cluster
      placeholder: "The COE Cluster information. `openstack coe cluster show --format json CLUSTER_NAME`"

  - type: textarea
    id: additional
    attributes:
      label: Anything else you would like to add?
      placeholder: "Miscellaneous information that will assist in solving the issue."

  - type: textarea
    id: templateLabel
    attributes:
      label: Label(s) to be applied
      value: |
        /kind bug
        One or more /area label. See https://github.com/vexxhost/magnum-cluster-api/labels?q=area for the list of labels.
